export const REPORT_TABLE_COLUMNS_NAMES: { [key: string]: string } = {
  orders: "Заказы",
  ordersCount: "Заказы шт",
  name: "Название товара",
  vendorCode: "Артикул продавца",
  brand: "Бренд",
  category: "Категория",
  article: "Артикул WB",
  cost: "Себестоимость",
  averagePriceBeforeSPP: "Средняя цена до СПП",
  realisation: "Реализация (сумма продаж до СПП)",
  sale: "Продажа",
  toTransfer: "К перечислению",
  returns: "Возвраты",
  costOfSales: "Себестоимость продаж",
  fines: "Штрафы",
  compensationForSubstitutedGoods: "Компенсация подмененного товара",
  reimbursementOfTransportationCosts: "Компенсация поставщика",
  paymentForMarriageAndLostGoods: "Оплата брака + потерянного товара",
  averageLogisticsCost: "Ср. стоимость логистики",
  logistics: "Логистика",
  storage: "Хранение",
  rejectionsAndReturns: "Количество отказов + возвраты",
  totalSales: "Общее количество продаж, с учетом возвратов",
  averageRedemption: "Средний процент выкупа",
  averageProfitPerPiece: "Средняя прибыль на 1 шт",
  tax: "Налог",
  profit: "Прибыль",
  roi: "ROI",
  profitability: "Рентабельность",
  shareInTotalRevenuePart: "Доля в общей выручке",
  shareInTotalProfit: "Доля в общей прибыли",
  marginality: "Маржинальность",
  advertisingExpenses: "Рекламные расходы",
  ddr: "ДРР",
};

export const SIZES_ROWS_FOR_REPORT_TABLE = [
  { label: "10", value: 10 },
  { label: "30", value: 30 },
  { label: "50", value: 50 },
];
