export const ROUTES = {
  login: "/login",
  registration: "/registration",
  logout: "/logout",
  resetPassword: "/reset-password",
  resetPasswordByToken: "/reset-password-with-token/:token",
  home: "/",
  week: "/week",
  pnl: "/pnl",
  authVk: "/auth/vk",
  authYandex: "/auth/yandex",
  unitTable: "/unit-table",
  settingsApiKeys: "/settings/api-keys",
  settings: "/settings/:tab?",
  settingsProfile: "/settings/profile",
  cost: "/cost",
  product: "/product",
  adminPanel: "/admin_panel",
  usersList: "/users_list",
  userInfo: "/user-info",
  tasksQueue: "/task-queue",
  otherExpenses: "/other-expenses",
  otherDeductions: "/other-deductions",
} as const;
