name: Deploy to Kubernetes

on:
  push:
    branches:
      - '*dev*'

jobs:
  deploy:
    runs-on: Blue-Yttrium
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load ENV
        run: |
          echo "${{ vars.DEV_ENV_FILE }}" > .env

      - name: Build container image
        run: docker build -t frontend . 

      - name: stop container 
        run: |
          echo ${{secrets.pwd}} | sudo -S docker stop frontend | true
          echo ${{secrets.pwd}} | sudo -S docker rm frontend | true

      - name: start container       
        run: echo ${{secrets.pwd}} | sudo -S docker run -d --name=frontend -p 127.0.0.1:3000:3000 frontend
