name: Deploy to Kubernetes

on:
  push:
    branches:
      - '*dev*'

jobs:
  deploy:
    runs-on: Blue-Yttrium
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -f ./.github/workflows/Dockerfile -t frontend . 

      - name: copy data from container
        run: docker cp $(docker create --name tmp frontend):/app/ /var/www/www-root/data/www/app.truestat.online_temp && docker rm tmp


